### PR TITLE
Update to 1.14.1 & Bugfixes

### PR DESCRIPTION
**Pull request by t3rminus**
This PR updates the build to 1.14

Also includes a couple of fixes for issues I encountered:
- some plugins don't work properly when the /plugins/ folder is not in the default location (CoreProtect)
- The "run as user" changes weren't working at all, and many directories (eg. world) were still being mounted as root

### CODE REVIEW

**Comment by FelixKlauke** [comment]
Hey,

thanks for you interest. I updated the Java Version to 11, as this ist the current LTS version. 12 would be a bit too much (even 11 will cause several problems because of the new class loader semantics of version 9).

I'm still investigating the issues with broken permissions.

It shouldn't be my task to fix plugins that are using wrong plugin directories, but I think it would be much smoother when we just symlink the "normal" plugins directory as a workaround.

Thanks for your help!

**Comment by t3rminus** [comment]
With regards to the JVM, you'll notice that change was reverted in this PR. When I first submitted it, I was incorrectly assuming the version listed above was actually the one being used to run minecraft, and not just for the build step.

As for the plugins folder, I agree it shouldn't be your job to work-around buggy plugins, but given the state of bukkit/spigot/paper plugin development right now, it's very likely that many of them are still in use, but will never be updated.

CoreProtect is still in development, I believe, but is a fairly essential plugin for anti-griefing. As annoying as it seems, putting the plugins directory back in the default spot allowed me to actually use this docker plugin in a live environment, and not as a curiosity or test system.

It's not as "clean", I agree, but it was necessary.

**Comment by FelixKlauke** [comment]
I still think it would be better to just add a symlink, I will add this asap. Furthermore I made a Bug Report to CoreProtect and the author will fix the directory in the next version:

BugReport

Did I forget something else to fix?

**Comment by t3rminus** [comment]
I believe that's it.

FYI The Paper-1.14/lastSuccessfulBuild is currently going to produce a build for 1.14.2, not 1.14.1.
I'm not sure if you want to track these versions separately. You may want to simply tag your builds as 1.14/1.13/1.12... etc, to avoid having to deal with the frequently-changing bugfixes.

**Comment by FelixKlauke** [comment]
I added 1.14.1 1.14.2 steps. I have to update the CI config whenever a new version is released. Can you clarify what you mean with those tags? What do I do different?

**Comment by t3rminus** [comment]
> Can you clarify what you mean with those tags? What do I do different?

I just mean use 1.14, 1.13, 1.10. See #21

**Comment by FelixKlauke** [comment]
According to https://www.spigotmc.org/resources/coreprotect.8631/update?update=280326 CoreProtect now supports custom plugin folders 👏

**Pull request closed without merging**
