### PR TITLE
Revert to java 8, to prevent frequent crashes

### PR DESCRIPTION
**Pull request by t3rminus**
Been testing this one for a while... 
My server was crashing multiple times per day, even when no players were online. Often with players online. Sometimes more than 4 times per hour.

I've lost the exact logs, since I've re-created the container so many times, but they were always SEGFAULT or similar, serious JVM-level crashes.

I've tested for a while on java 10, and experienced similar issues.

It was only when I re-created the container with an openjdk-8 base did the crashes stop, and my players could play uninterrupted for days at a time.

### CODE REVIEW

**Comment by FelixKlauke** [comment]
Would be really interesting to see the corresponding log files! Could you try to get some? (Even after crash the container is still there and you can get the log files e.g. with `docker copy`. I hesitate to use Java 8 everywhere as some plugins are already compiled for Java 11. 

I will do some research on the memory management of java processes in docker as this is a quite complex topic. Java 11 for instance brings auto management is aware of the container memory, while Java 8 doesn't do that.

**Comment by t3rminus** [comment]
Java 8 is aware of container memory limits with the flags `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` although they’re considered experimental (according to https://hub.docker.com/_/openjdk)
They are included in this PR.

I’ve killed the old containers fo run my own java-8 version, but I’ll re-deploy the Java 11 version and get some log files.

**Comment by FelixKlauke** [comment]
That matches the things I found out. That could be a valid workaround if we stick to Java 8. I would still wait for some research on the crashes. Thank you for your help!

**Comment by t3rminus** [comment]
Here are a couple of crash logs from a duplicate of the server I created, and tried to run for the past 8 hours. It's crashed 5 times.

Here's a few of the crash dumps. (There are no other errors before the crashes)

[crash1.txt](https://github.com/FelixKlauke/paperspigot-docker/files/3658564/crash1.txt)
[crash2.txt](https://github.com/FelixKlauke/paperspigot-docker/files/3658562/crash2.txt)
[crash3.txt](https://github.com/FelixKlauke/paperspigot-docker/files/3658563/crash3.txt)

**Comment by FelixKlauke** [comment]
Can anyone else confirm this behaviour? There are already plenty of servers using Java 11 in their plugins and I wouldn't like to downgrade this if it's not absolutely necessary. I even would like to switch to Java 13 in the next version and to Java 15 in September. Keeping the versions so much behind might be good for legacy projects, but that should not be the mainstream use case.

**Comment by t3rminus** [comment]
Honestly, it was probably an issue with my exact install, and likely a coincidence that Java 8 was less prone to crashing.

I’ve moved away from using this docker for unrelated reasons now, so I can’t even confirm if this is still an issue on my end.

I’m fine to close this.

**Pull request closed without merging**
